# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'Player')),
                ('player_jersey_no', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_matches', models.CharField(blank=True, max_length=100, null=True)),
                ('no_runs', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_scores', models.CharField(blank=True, max_length=100, null=True)),
                ('no_fifties', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hundreds', models.CharField(blank=True, max_length=100, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('contestant1_points', models.CharField(blank=True, max_length=100, null=True)),
                ('contestant2_points', models.CharField(blank=True, max_length=100, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Matches')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'Team')),
                ('club_state', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='team.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='contestant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_winner_contestant1', to='team.Team'),
        ),
        migrations.AddField(
            model_name='matches',
            name='contestant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_winner_contestant2', to='team.Team'),
        ),
    ]
